#!/bin/bash
#
# Add video backgrounds to StepMania songs that don't have one, by downloading
# each song's MV from YouTube (yt-dlp), trimming it to the song's length and
# re-encoding to a StepMania-5.1-compatible format (ffmpeg), then wiring it
# into the .sm via #BGCHANGES.
#
# Compatibility: SM 5.1's bundled ffmpeg is old — modern YouTube codecs (AV1,
# VP9) won't decode in-game, but H.264 does (verified against a set of mp4s
# known to play in this user's SM 5.1: h264 Baseline/Main/High, yuv420p, up to
# 1080p). Videos are re-encoded to H.264 mp4, video-only, 1080p max @30fps,
# crf 23 — roughly 2-3x better quality per byte than the packs' legacy
# MPEG-4/AVI files. Set MAX_H=720 to halve file sizes if space matters.
#
# Usage:
#   bash add-mv-backgrounds.sh PACK_DIR [--dry-run] [--limit N] [--fix]
#     PACK_DIR   a pack folder containing song dirs (e.g. Songs/Mintmania)
#     --dry-run  show what would be done, download nothing
#     --limit N  process at most N songs (default: all)
#     --fix      also re-download/re-generate songs whose existing video is a
#                script-generated mv-bg.mp4 (e.g. made by an older version of
#                this script, before the fade-out / candidate filtering).
#                Videos already made by the current pipeline are detected
#                (metadata version tag, or faded ending for pre-tag files)
#                and skipped — so an aborted --fix run can simply be re-run
#                and it resumes where it left off.
#                Hand-placed videos (any other filename) are never touched.
#
# Per song it:
#   1. Skips if a video file already exists, or #BGCHANGES is non-empty
#      (don't clobber authored background scripts).
#   2. Reads #TITLE/#ARTIST (+translit fallbacks) and the audio length.
#   3. Scans YouTube search results ("<artist> <title> MV") in pages of 10,
#      skipping candidates that are shorter than the chart or are a static
#      image with audio, until a good MV is found (N_CAND=-1 default; set
#      N_CAND=5 to only consider the top 5, MAX_SCAN to move the hard stop).
#      If the first 3 candidates are all rejected, the search is retried
#      WITHOUT the artist name — many old MV uploads don't carry it in the
#      title, so the broader query often succeeds where the strict one fails.
#      Logs the matched video title so you can review mismatches afterwards.
#   4. Trims to audio length + 2s, re-encodes, writes <songdir>/mv-bg.avi.
#   5. Backs up the .sm to .sm.mvbak, sets
#      #BGCHANGES:0.000=mv-bg.avi=1.000=1=1=0;   (the pack's own convention)
#
# Review note: an MV is background eye-candy, not beat-synced — remixes
# (e.g. "euro mix" charts) will drift from the original MV's visuals. Delete
# mv-bg.avi and restore the .sm.mvbak for any song where it doesn't work.
#
set -uo pipefail

PACK_DIR="${1:-}"
DRY_RUN=0
LIMIT=0
FIX=0
shift || true
while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY_RUN=1 ;;
        --limit) shift; LIMIT="${1:-0}" ;;
        --fix) FIX=1 ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
    shift
done

[ -d "$PACK_DIR" ] || { echo "Usage: bash $0 PACK_DIR [--dry-run] [--limit N] [--fix]" >&2; exit 1; }
for tool in yt-dlp ffmpeg ffprobe; do
    command -v "$tool" >/dev/null || { echo "ERROR: $tool not installed" >&2; exit 1; }
done

VIDEO_NAME="mv-bg.mp4"
GEN_VERSION="2"            # stamped into generated files (mp4 comment tag);
                           # bump when the pipeline changes so --fix knows
                           # which existing videos are outdated
MAX_H="${MAX_H:-1080}"     # max video height; override e.g. MAX_H=720 to halve file sizes
N_CAND="${N_CAND:--1}"     # search results to consider per song; -1 = keep going
MAX_SCAN="${MAX_SCAN:-50}" # hard stop for N_CAND=-1 (search relevance dies off anyway)
PAGE=10                    # results fetched per search request when paging
MIN_MOTION="${MIN_MOTION:-2.0}"  # mean YDIF below this = static image-like, reject
LOG="$PACK_DIR/mv-backgrounds.log"
tag() {  # $1=file $2=tagname -> value (first match, CR stripped)
    grep -m1 -oP "(?<=#$2:)[^;]*" "$1" 2>/dev/null | tr -d '\r' || true
}

# Static-image detection: mean inter-frame luma difference (YDIF) over the
# first 60s, sampled at 2fps. Real MVs measure 20-40; a still image with
# audio measures ~0.003. Returns 0 (true) when the video is static-like.
is_static() {
    local mean
    mean=$(ffmpeg -loglevel info -t 60 -i "$1" -an \
                  -vf "fps=2,signalstats,metadata=print:key=lavfi.signalstats.YDIF" \
                  -f null - 2>&1 </dev/null \
           | grep -oP 'YDIF=\K[\d.]+' \
           | awk '{s+=$1; n++} END{if(n>0) print s/n; else print 0}')
    awk -v m="$mean" -v t="$MIN_MOTION" 'BEGIN{exit !(m < t)}'
}

# Was this video generated by the CURRENT pipeline? Used by --fix to skip
# work that's already done (e.g. when resuming an aborted run).
#   1. Version tag: new files carry "add-mv-backgrounds v$GEN_VERSION" in the
#      mp4 comment metadata — authoritative.
#   2. Fade heuristic (for current-pipeline files made before tagging existed):
#      our encodes fade to black over the last 2s, so the last half-second
#      averages ~20 luma; an old-version hard mid-video cut measures 40-100.
is_fixed() {
    local tagval luma
    tagval=$(ffprobe -v error -show_entries format_tags=comment -of csv=p=0 "$1" 2>/dev/null </dev/null)
    case "$tagval" in *"add-mv-backgrounds v$GEN_VERSION"*) return 0 ;; esac
    luma=$(ffmpeg -loglevel info -sseof -0.5 -i "$1" -an \
                  -vf "signalstats,metadata=print:key=lavfi.signalstats.YAVG" \
                  -f null - 2>&1 </dev/null \
           | grep -oP 'YAVG=\K[\d.]+' | awk '{s+=$1;n++} END{print (n? s/n : 255)}')
    awk -v l="$luma" 'BEGIN{exit !(l < 25)}'
}

# Scan search results page by page for a usable MV, rejecting candidates that
# are shorter than the chart or static-image-like.
#   $1 = search query
#   $2 = rejection budget: stop after this many rejected candidates (0 = no
#        budget — scan until success, search exhaustion, or the scan cap)
# Uses: $dur (chart length), $tmp (work dir). Sets $src/$picked on success.
# Scan cap: N_CAND>0 bounds the scan; N_CAND=-1 keeps going up to MAX_SCAN.
scan_for_mv() {
    local query="$1" budget="$2"
    local scan_max start end batch vid vdur vtitle cand rejects=0
    scan_max=$([ "$N_CAND" -gt 0 ] && echo "$N_CAND" || echo "$MAX_SCAN")
    start=1
    while [ -z "$src" ] && [ "$start" -le "$scan_max" ]; do
        end=$((start + PAGE - 1)); [ "$end" -gt "$scan_max" ] && end="$scan_max"
        batch=$(yt-dlp --js-runtimes node --no-playlist --quiet --no-warnings \
                       --playlist-items "$start:$end" \
                       --print "%(id)s|%(duration)s|%(title)s" \
                       "ytsearch$end:$query" 2>/dev/null </dev/null)
        [ -n "$batch" ] || break
        while IFS='|' read -r vid vdur vtitle; do
            [ -n "$vid" ] || continue
            vdur=${vdur%%.*}
            if ! [[ "$vdur" =~ ^[0-9]+$ ]] || [ "$vdur" -lt "$dur" ]; then
                echo "  reject (${vdur:-?}s < chart ${dur}s): $vtitle"
                rejects=$((rejects+1))
                [ "$budget" -gt 0 ] && [ "$rejects" -ge "$budget" ] && return 1
                continue
            fi
            rm -f "$tmp"/dl.*
            if ! yt-dlp --js-runtimes node --no-playlist --quiet --no-warnings \
                    -f "bv*[height<=$MAX_H]+ba/b[height<=$MAX_H]/b" \
                    -o "$tmp/dl.%(ext)s" "https://www.youtube.com/watch?v=$vid" 2>/dev/null </dev/null; then
                echo "  reject (download failed): $vtitle"
                rejects=$((rejects+1))
                [ "$budget" -gt 0 ] && [ "$rejects" -ge "$budget" ] && return 1
                continue
            fi
            cand=$(ls "$tmp"/dl.* 2>/dev/null | head -1)
            [ -n "$cand" ] || continue
            if is_static "$cand"; then
                echo "  reject (static image-like): $vtitle"
                rejects=$((rejects+1))
                [ "$budget" -gt 0 ] && [ "$rejects" -ge "$budget" ] && return 1
                continue
            fi
            src="$cand"
            picked="$vtitle [$vid] ${vdur}s"
            return 0
        done <<< "$batch"
        # Fewer lines than requested = search exhausted; stop paging.
        [ "$(wc -l <<< "$batch")" -lt $((end - start + 1)) ] && break
        start=$((end + 1))
    done
    [ -n "$src" ]
}

done_n=0 skipped=0 failed=0
for songdir in "$PACK_DIR"/*/; do
    [ -d "$songdir" ] || continue
    [ "$LIMIT" -gt 0 ] && [ "$done_n" -ge "$LIMIT" ] && break
    name=$(basename "$songdir")

    # Existing video? Normally skip. With --fix, regenerate when the only
    # video is our own script-generated $VIDEO_NAME (never touch hand-placed
    # videos, which have other filenames).
    regen=0
    existing=$(find "$songdir" -maxdepth 1 -iregex '.*\.\(avi\|mp4\|mpg\|mpeg\|mkv\|wmv\|flv\)')
    if [ -n "$existing" ]; then
        others=$(echo "$existing" | grep -v "/$VIDEO_NAME\$" || true)
        if [ "$FIX" -eq 1 ] && [ -z "$others" ]; then
            if is_fixed "$songdir$VIDEO_NAME"; then
                echo "  skip (already fixed): $name"
                skipped=$((skipped+1)); continue
            fi
            regen=1
        else
            skipped=$((skipped+1)); continue
        fi
    fi
    sm=$(find "$songdir" -maxdepth 1 \( -iname '*.sm' -o -iname '*.ssc' \) | head -1)
    [ -n "$sm" ] || { skipped=$((skipped+1)); continue; }

    # Skip: authored BGCHANGES already present. A BGCHANGES that references
    # our own $VIDEO_NAME is fine when regenerating.
    bg=$(tag "$sm" BGCHANGES)
    if [ -n "$bg" ]; then
        case "$bg" in
            *"$VIDEO_NAME"*) [ "$regen" -eq 1 ] || { skipped=$((skipped+1)); continue; } ;;
            *) echo "  skip (has BGCHANGES): $name"; skipped=$((skipped+1)); continue ;;
        esac
    fi
    [ "$regen" -eq 1 ] && echo "[$name] fix: regenerating $VIDEO_NAME"

    title=$(tag "$sm" TITLE);  [ -n "$title" ]  || title=$(tag "$sm" TITLETRANSLIT)
    artist=$(tag "$sm" ARTIST); [ -n "$artist" ] || artist=$(tag "$sm" ARTISTTRANSLIT)
    if [ -z "$title" ]; then
        echo "  skip (no title): $name"; skipped=$((skipped+1)); continue
    fi

    # Audio length (from #MUSIC, else first audio file found)
    music=$(tag "$sm" MUSIC)
    audio="$songdir$music"
    [ -f "$audio" ] || audio=$(find "$songdir" -maxdepth 1 \( -iname '*.ogg' -o -iname '*.mp3' -o -iname '*.wav' \) | head -1)
    [ -f "$audio" ] || { echo "  skip (no audio): $name"; skipped=$((skipped+1)); continue; }
    dur=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$audio" | cut -d. -f1)
    [ -n "$dur" ] && [ "$dur" -gt 0 ] || { echo "  skip (no duration): $name"; skipped=$((skipped+1)); continue; }
    clip=$((dur + 2))

    query="$artist $title MV"
    echo "[$name] '$artist - $title' (${dur}s) — searching: $query"
    if [ "$DRY_RUN" -eq 1 ]; then
        done_n=$((done_n+1)); continue
    fi

    tmp=$(mktemp -d -t mvbg-XXXXXX)
    # Try with the artist name first; if the first 3 candidates are all
    # rejected, retry without it — many old MV uploads don't carry the artist
    # in the title, so the broader query often finds a good one.
    src=""; picked=""
    scan_for_mv "$query" 3
    if [ -z "$src" ] && [ -n "$artist" ]; then
        echo "  retrying without artist name: $title MV"
        scan_for_mv "$title MV" 0
    fi
    if [ -z "$src" ]; then
        echo "  FAILED (no usable candidate)"
        failed=$((failed+1)); rm -rf "$tmp"; continue
    fi
    echo "  matched: $picked"
    # Fade to black over the last 2s instead of a hard cut. The fade anchors to
    # whichever ends first — the trimmed clip, or the MV itself if it's shorter.
    end="$clip"
    if [ -n "$src" ]; then
        src_dur=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$src" 2>/dev/null | cut -d. -f1)
        if [ -n "$src_dur" ] && [ "$src_dur" -gt 0 ] && [ "$src_dur" -lt "$clip" ]; then
            end="$src_dur"
        fi
    fi
    # Encode to a temp file first so a failed (re-)encode never destroys an
    # existing video; move into place only on success.
    if [ -z "$src" ] || ! ffmpeg -y -loglevel error -i "$src" -t "$clip" -an \
            -vf "scale='min($((MAX_H*16/9)),iw)':-2,fade=t=out:st=$((end-2)):d=2" -r 30 \
            -c:v libx264 -profile:v high -pix_fmt yuv420p -crf 23 -preset fast \
            -metadata comment="add-mv-backgrounds v$GEN_VERSION" \
            "$tmp/out.mp4" </dev/null; then
        echo "  FAILED (encode)"; failed=$((failed+1)); rm -rf "$tmp"; continue
    fi
    mv "$tmp/out.mp4" "$songdir$VIDEO_NAME"
    rm -rf "$tmp"

    # Wire into the .sm: replace the empty #BGCHANGES:; (CRLF-safe). Skip when
    # already wired (e.g. --fix regeneration) — also keeps the existing
    # .mvbak backup pristine instead of overwriting it with an edited copy.
    if ! grep -q "=$VIDEO_NAME=" "$sm"; then
        cp "$sm" "$sm.mvbak"
        if grep -q '^#BGCHANGES:;' "$sm"; then
            sed -i "s|^#BGCHANGES:;|#BGCHANGES:0.000=$VIDEO_NAME=1.000=1=1=0;|" "$sm"
        elif grep -q $'^#BGCHANGES:;\r' "$sm"; then
            sed -i "s|^#BGCHANGES:;\r|#BGCHANGES:0.000=$VIDEO_NAME=1.000=1=1=0;\r|" "$sm"
        else
            # No #BGCHANGES tag at all — append one
            printf '#BGCHANGES:0.000=%s=1.000=1=1=0;\n' "$VIDEO_NAME" >> "$sm"
        fi
    fi
    size=$(ls -lh "$songdir$VIDEO_NAME" | awk '{print $5}')
    echo "  done: $VIDEO_NAME ($size, ${clip}s)"
    printf '%s | %s - %s | %s\n' "$name" "$artist" "$title" "$picked" >> "$LOG"
    done_n=$((done_n+1))
done

echo
echo "Done. processed=$done_n skipped=$skipped failed=$failed"
[ -f "$LOG" ] && echo "Review matches in: $LOG  (delete $VIDEO_NAME + restore .sm.mvbak for any mismatch)"
exit 0
